# Generated by Django 2.1.5 on 2019-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField(blank=True, max_length=15)),
                ('nonce', models.IntegerField(blank=True)),
                ('msg', models.TextField(blank=True, max_length=3)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
