# Generated by Django 2.1.5 on 2019-10-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='msg',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
