# Generated by Django 3.2.6 on 2021-08-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouse', '0002_auto_20191007_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.TextField(blank=True),
        ),
    ]
